language: php

php:
  - 7.0
  - 7.1

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan jwt:generate
  - php artisan migrate
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

before_install:
  - mysql -e 'CREATE DATABASE test;'

script:
  - vendor/bin/phpunit

services:
  - mysql

notifications:
  email: false