language: php

php:
  - 7.0
  - 7.1

before_script:
  - cp .env.travis .env
  - php artisan key:generate
  - php artisan jwt:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE test;'

script:
  - phpunit

services:
  - mysql

notifications:
  email: false