language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate:install --no-interaction -vvv
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit

services:
  - mysql

notifications:
    email:
      recipients:
        - kjsmith.dev@gmail.com
      on_success: never # default: change
      on_failure: never # default: always
